---
- hosts: angular_frontend
  vars:
    job_roles_dir: "../../roles"  # just a shortcut to avoid "ugly dots and slashes" in role names ;)

  roles:
    - { role: beam.git, action: deploy }

    - { role: beam.nodejs, action: deploy}

    - { role: beam.compass, action: deploy}

    - { role: "{{ job_roles_dir }}/common-tasks", action: deploy}

    - { role: beam.nginx, action: deploy, params: {
          nginx_domain: localhost,
          nginx_host: 127.0.0.1,
          nginx_port: 8080,
          nginx_client_max_body_size: 100K,
          nginx_project_name: "{{ BEAM_VARS.COMPONENT.NAME }}",
          nginx_site_conf_file_template: templates/nginx_angular_app.conf
        }
      }

